### ISSUE TITLE
Cyclic mod dependency

### ISSUE THREAD

**Issue by SolariusScorch** [emipa606/MedicalSupplements#1]
Hi Mlie,
I seem to be getting a cyclic mod dependency warning starting from this mod. When I enable it, several others - Common Ailments (Continued), Emporium (Continued), and Fermenter (Continued) - go red.
Not sure if it's an issue on my end, so I thought I'd let you know.

EDIT: Same with utility supplements. Weird.

**Comment by emipa606** [comment]
Should be fixed now. There were cyclic dependencies between the mods in the patches and I did not notice it. 
I have moved all patches to the dependent mod in each case so there should be no problems any more.
Thanks for reporting!

**Comment by SolariusScorch** [comment]
Thank you for all the great work you're doing!

**Comment by SolariusScorch** [comment]
Hi! Still experiencing some issues, this time between Apothecary, Utility Supplements, Medical Supplements and Emporium. I redownloaded them all from GitHub (using GoG version of Rimworld, so no automatic updates for me) and the problem persists. Disabling Apothecary removes the issue, though according to the report, the cyclical dependency starts with Medical Supplements.
Do you think it's a problem on my end?

**Comment by emipa606** [comment]
Im not sure I can replicate this, Here is the mod-order in my test that has no issues:
![image](https://user-images.githubusercontent.com/6932991/90237521-afedaf00-de24-11ea-952b-701dcf537824.png)
If you are using the github versions I might suggest using the ModCheck-mod as all my mods have support for it:
https://github.com/KiameV/rimworld-modsync-rw/releases/latest

**Comment by SolariusScorch** [comment]
First of all, thanks for the prompt response. I can't imagine how many questions you get all the time.
Secondly, wow, this ModSync tool is fantastic, thanks. But all my mods were already updated (except SYR_Naga, but it's unrelated.)
Thirdly, unfortunately I'm still getting nowhere. After enabling Medical Supplements, what I'm getting is this:
![obraz](https://user-images.githubusercontent.com/7339969/90240957-77e96a80-de2a-11ea-8b73-0e378e66b073.png)
These mods were fine before enabling Medical Supplements. And enabling Apothecary disables Medical Supplements.
When messing around with load order, I get different errors.
If you're sure your mods are fine, then it's something on my end and I'll bugger off... But I can't think of any particular issue, sorry.

**Comment by emipa606** [comment]
I see, I didnt know you had the other mods as well. Should be fixed now. 
Been a few hectic days fixing all 25 mods of pelador so I must have missed testing all together, thanks for reporting!

**Comment by SolariusScorch** [comment]
Again, many thanks for your patience for one random player. I'm also a modder (though not for RW) and I totally get how overwhelming it can be when lots of random people demand a little bit of your attention. :)
I have updated everything I could, but darn, still plagued by various cyclic dependencies. I'll probably drop some mods to avoid the issue - I can live without Common Ailments, for example. But if there's anything I can do to help - provide logs or whatever - please let me know.
BTW is this normal that my ModSyncRW window looks like this?
![captureModSyncRW](https://user-images.githubusercontent.com/7339969/90310624-95ced200-def3-11ea-9deb-3b27d9590774.png)
I'm like 20% down the list, and the list ends... Might be something like that bug with the trade screen when the list disappears after you slide to a certain place?

**Comment by emipa606** [comment]
From what I can see from your update-window the Apothecary-mod is still the first release?
Can you check the Manifest-file or the ModSync-file and verify that it is the 1.0.3-version downloaded?

**Comment by SolariusScorch** [comment]
Apothecary version is 1.0.3.0, according to Manifest.xml.

**Comment by SolariusScorch** [comment]
All problems solved!
Thank you for the terrific job you're doing for the RW community.

**Comment by emipa606** [comment]
Great to hear!
